#!/usr/bin/env bash

set -x

#
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc
#
# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="5"
gaps["bottom"]="4"
gaps["left"]="5"
gaps["right"]="5"
gaps["inner"]="5"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

# focus_follows_mouse [autofocus|autoraise|off]
yabai -m config focus_follows_mouse         off

yabai -m config split_ratio                 0.50

yabai -m config split_type                  auto

yabai -m config auto_balance                off

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config external_bar all:37:0

# ===== Rules ==================================
# Find app name: `yabai -m query --windows`
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="MonitorControl" app="^MonitorControl$" manage=off
yabai -m rule --add label="AltTab" app="^AltTab$" manage=off
yabai -m rule --add label="League of Legends" app="^League of Legends$" manage=off

# ===== Signals ================================

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=application_launched action="sketchybar --trigger window_focus"
yabai -m signal --add event=application_terminated action="sketchybar --trigger window_focus"

yabai -m signal --add event=display_added action="fish -c 'source ~/code/dotfiles/yabai/helpers.fish; yabai_display_added'"


set +x
printf "yabai: configuration loaded...\\n"
